DEBUG 2015-04-02 12:55:33,697: 	 Executing command: 'kill'
DEBUG 2015-04-02 12:55:33,697: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-02 12:56:30,004: 	 Executing command: 'purge'
DEBUG 2015-04-02 12:56:30,004: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-02 12:56:50,861: 	 Executing command: 'status'
DEBUG 2015-04-02 12:56:50,861: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-02 12:56:50,869: 	 Checking credentials
DEBUG 2015-04-02 12:56:50,869: 	 Found proxy file /tmp/x509up_u23766
DEBUG 2015-04-02 12:56:50,869: 	 Getting proxy life time left
DEBUG 2015-04-02 12:56:51,272: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -timeleft
 output : 689677

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-02 12:56:51,674: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -actimeleft
 output : 689677

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-02 12:56:51,674: 	 Proxy valid for 191:34:37 hours
ERROR 2015-04-02 12:56:51,675: 	 Cannot find .requestcache file inside the working directory for task crab_projects
ERROR 2015-04-02 12:56:51,675: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 288, in __init__
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 397, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 388, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file inside the working directory for task crab_projects
DEBUG 2015-04-02 14:06:32,742: 	 Executing command: 'submit'
DEBUG 2015-04-02 14:06:32,742: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-02 14:06:32,784: 	 Checking credentials
DEBUG 2015-04-02 14:06:32,784: 	 Found proxy file /tmp/x509up_u23766
DEBUG 2015-04-02 14:06:32,784: 	 Getting proxy life time left
DEBUG 2015-04-02 14:06:33,287: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -timeleft
 output : 685495

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-02 14:06:33,789: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -actimeleft
 output : 685495

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-02 14:06:33,790: 	 Proxy valid for 190:24:55 hours
ERROR 2015-04-02 14:06:33,790: 	 Configuration file 'crab_QCD4Jets_Pt-100to180_TuneZ2Star_8TeV_alpgen_BTagJetTrackSel.py' not found.
ERROR 2015-04-02 14:06:33,790: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 264, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    raise ConfigurationException("Configuration file '%s' not found." % configname)
ConfigurationException: Configuration file 'crab_QCD4Jets_Pt-100to180_TuneZ2Star_8TeV_alpgen_BTagJetTrackSel.py' not found.
DEBUG 2015-04-02 14:10:08,792: 	 Executing command: 'submit'
DEBUG 2015-04-02 14:10:08,792: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-02 14:10:08,797: 	 Checking credentials
DEBUG 2015-04-02 14:10:08,798: 	 Found proxy file /tmp/x509up_u23766
DEBUG 2015-04-02 14:10:08,798: 	 Getting proxy life time left
DEBUG 2015-04-02 14:10:09,701: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -timeleft
 output : 685279

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-02 14:10:10,305: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -actimeleft
 output : 685278

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-02 14:10:10,305: 	 Proxy valid for 190:21:19 hours
ERROR 2015-04-02 14:10:10,305: 	 Configuration file 'crab_QCD_Pt-50to80_MuEnrichedPt5_PionKaonDecay_Tune4C_13TeV_pythia8_BTagJetTrackSel.py' not found.
ERROR 2015-04-02 14:10:10,306: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 264, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    raise ConfigurationException("Configuration file '%s' not found." % configname)
ConfigurationException: Configuration file 'crab_QCD_Pt-50to80_MuEnrichedPt5_PionKaonDecay_Tune4C_13TeV_pythia8_BTagJetTrackSel.py' not found.
DEBUG 2015-04-02 14:22:21,935: 	 Executing command: 'status'
DEBUG 2015-04-02 14:22:21,935: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-02 14:22:21,941: 	 Checking credentials
DEBUG 2015-04-02 14:22:21,941: 	 Found proxy file /tmp/x509up_u23766
DEBUG 2015-04-02 14:22:21,941: 	 Getting proxy life time left
DEBUG 2015-04-02 14:22:22,443: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -timeleft
 output : 684546

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-02 14:22:22,850: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -actimeleft
 output : 684546

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-02 14:22:22,850: 	 Proxy valid for 190:09:06 hours
ERROR 2015-04-02 14:22:22,851: 	 Working directory for task crab_MC_AlpGen_QCD4Jets_Pt-100to180_TuneZ2Star_8TeV not found 
ERROR 2015-04-02 14:22:22,851: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 288, in __init__
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 397, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 382, in loadCache
    raise TaskNotFoundException(msg)
TaskNotFoundException: Working directory for task crab_MC_AlpGen_QCD4Jets_Pt-100to180_TuneZ2Star_8TeV not found 
DEBUG 2015-04-02 18:15:31,142: 	 Executing command: 'resubmit'
DEBUG 2015-04-02 18:15:31,143: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-07 10:24:37,490: 	 Executing command: 'status'
DEBUG 2015-04-07 10:24:37,513: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-07 10:24:37,528: 	 Checking credentials
DEBUG 2015-04-07 10:24:37,528: 	 Found proxy file /tmp/x509up_u23766
DEBUG 2015-04-07 10:24:37,528: 	 Getting proxy life time left
DEBUG 2015-04-07 10:24:38,431: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -timeleft
 output : 266810

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-07 10:24:38,834: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -actimeleft
 output : 266810

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-07 10:24:38,834: 	 Proxy valid for 74:06:50 hours
ERROR 2015-04-07 10:24:38,835: 	 Working directory for task crab_MC_AlpGen_QCD4Jets_Pt-100to180_TuneZ2Star_8TeV not found 
ERROR 2015-04-07 10:24:38,835: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 288, in __init__
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 397, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 382, in loadCache
    raise TaskNotFoundException(msg)
TaskNotFoundException: Working directory for task crab_MC_AlpGen_QCD4Jets_Pt-100to180_TuneZ2Star_8TeV not found 
DEBUG 2015-04-07 18:27:27,052: 	 Executing command: 'kill'
DEBUG 2015-04-07 18:27:27,052: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-07 18:27:27,058: 	 Checking credentials
DEBUG 2015-04-07 18:27:27,058: 	 Found proxy file /tmp/x509up_u23766
DEBUG 2015-04-07 18:27:27,058: 	 Getting proxy life time left
DEBUG 2015-04-07 18:27:27,460: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -timeleft
 output : 679775

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-07 18:27:27,862: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -actimeleft
 output : 679775

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-07 18:27:27,862: 	 Proxy valid for 188:49:35 hours
ERROR 2015-04-07 18:27:27,863: 	 Working directory for task crab_MC_MCatNLO_TT_8TeV not found 
ERROR 2015-04-07 18:27:27,863: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 288, in __init__
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 397, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14-comp/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 382, in loadCache
    raise TaskNotFoundException(msg)
TaskNotFoundException: Working directory for task crab_MC_MCatNLO_TT_8TeV not found 
DEBUG 2015-04-08 11:48:19,918: 	 Executing command: 'status'
DEBUG 2015-04-08 11:48:19,919: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-08 11:48:19,933: 	 Checking credentials
DEBUG 2015-04-08 11:48:19,934: 	 Found proxy file /tmp/x509up_u23766
DEBUG 2015-04-08 11:48:19,934: 	 Getting proxy life time left
DEBUG 2015-04-08 11:48:20,937: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -timeleft
 output : 617322

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
ERROR 2015-04-08 11:48:21,094: 	 Keyboard Interrupted
DEBUG 2015-04-10 09:54:10,318: 	 Executing command: 'status'
DEBUG 2015-04-10 09:54:10,319: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-10 10:01:01,813: 	 Executing command: 'kill'
DEBUG 2015-04-10 10:01:01,813: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-10 10:05:03,532: 	 Executing command: 'status'
DEBUG 2015-04-10 10:05:03,532: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-10 10:05:47,464: 	 Executing command: 'getlog'
DEBUG 2015-04-10 10:05:47,464: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-10 10:07:04,377: 	 Executing command: 'tasks'
DEBUG 2015-04-10 10:07:04,378: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-10 10:07:31,881: 	 Executing command: 'tasks'
DEBUG 2015-04-10 10:07:31,882: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
INFO 2015-04-10 10:07:32,056: 	 Task from previous 1 days
DEBUG 2015-04-10 10:07:32,065: 	 Checking credentials
DEBUG 2015-04-10 10:07:32,065: 	 Found proxy file /tmp/x509up_u23766
DEBUG 2015-04-10 10:07:32,065: 	 Getting proxy life time left
DEBUG 2015-04-10 10:07:32,467: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -timeleft
 output : 450570

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-10 10:07:32,870: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -actimeleft
 output : 450570

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-10 10:07:32,871: 	 Proxy valid for 125:09:30 hours
DEBUG 2015-04-10 10:07:32,977: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /C=DE/O=GermanGrid/OU=KIT/CN=Shawn Williamson

 error: WARNING: can't open config file: /build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/tmp/BUILDROOT/209fa2e8d4bb4119c53c263f5458541e/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/slc6_amd64_gcc481/external/openssl/1.0.1m/ssl/openssl.cnf

 retcode : 0
DEBUG 2015-04-10 10:07:32,977: 	 Checking credentials
DEBUG 2015-04-10 10:07:32,977: 	 Found proxy file /tmp/x509up_u23766
DEBUG 2015-04-10 10:07:32,977: 	 Getting proxy life time left
DEBUG 2015-04-10 10:07:33,380: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -timeleft
 output : 450569

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-10 10:07:33,783: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -actimeleft
 output : 450569

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-10 10:07:33,783: 	 Proxy valid for 125:09:29 hours
DEBUG 2015-04-10 10:07:34,186: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u23766 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL
/cms/dcms/Role=NULL/Capability=NULL

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-10 10:07:34,718: 	 Registering user credentials for server /DC=ch/DC=cern/OU=computers/CN=vocms(3[136]|21|045|052|021|031).cern.ch
DEBUG 2015-04-10 10:07:34,824: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /C=DE/O=GermanGrid/OU=KIT/CN=Shawn Williamson

 error: WARNING: can't open config file: /build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/tmp/BUILDROOT/209fa2e8d4bb4119c53c263f5458541e/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc481/w/slc6_amd64_gcc481/external/openssl/1.0.1m/ssl/openssl.cnf

 retcode : 0
DEBUG 2015-04-10 10:07:34,824: 	 Getting myproxy life time left for myproxy.cern.ch
DEBUG 2015-04-10 10:07:34,824: 	 Calculating hash of /C=DE/O=GermanGrid/OU=KIT/CN=Shawn Williamson_cmsweb.cern.ch for credential name
DEBUG 2015-04-10 10:07:35,327: 	 Executing : 
 command : myproxy-info -l 11609345f629d1bbab13420f7eb73c0aa60e9368 -s myproxy.cern.ch
 output : username: 11609345f629d1bbab13420f7eb73c0aa60e9368
owner: /C=DE/O=GermanGrid/OU=KIT/CN=Shawn Williamson
  renewal policy: /DC=ch/DC=cern/OU=computers/CN=vocms(3[136]|21|045|052|021|031).cern.ch
  trusted retrieval policy: /DC=ch/DC=cern/OU=computers/CN=vocms(3[136]|21|045|052|021|031).cern.ch
  timeleft: 530:25:21  (22.1 days)

 error: 
 retcode : 0
DEBUG 2015-04-10 10:07:35,328: 	 Myproxy is valid: 1909521
DEBUG 2015-04-10 10:07:35,328: 	 Command use: tasks
DEBUG 2015-04-10 10:07:35,328: 	 Options use: ['--days=1']
DEBUG 2015-04-10 10:07:35,913: 	 CRABClient version: 3.3.15 Compatible
DEBUG 2015-04-10 10:07:35,913: 	 Instance is prod
DEBUG 2015-04-10 10:07:35,913: 	 Server base url is cmsweb.cern.ch
DEBUG 2015-04-10 10:07:35,914: 	 Command url /crabserver/prod/workflow
INFO 2015-04-10 10:07:36,677: 	 

INFO 2015-04-10 10:07:36,677: 	 The list of tasks from 2015-04-09 until 2015-04-10
INFO 2015-04-10 10:07:36,677: 	 ================================================================================
INFO 2015-04-10 10:07:36,677: 	 NAME								STATUS
INFO 2015-04-10 10:07:36,677: 	 ================================================================================
INFO 2015-04-10 10:07:36,677: 	 150409_142123:shwillia_crab_MC_Powheg_Herwig_TT_CT10_AUET2_8TeV
								SUBMITTED
INFO 2015-04-10 10:07:36,677: 	 --------------------------------------------------------------------------------
INFO 2015-04-10 10:07:36,677: 	 

DEBUG 2015-04-10 10:08:21,813: 	 Executing command: 'getoutput'
DEBUG 2015-04-10 10:08:21,813: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-10 10:08:54,641: 	 Executing command: 'status'
DEBUG 2015-04-10 10:08:54,641: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-10 10:09:08,173: 	 Executing command: 'getlog'
DEBUG 2015-04-10 10:09:08,173: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-10 10:11:17,352: 	 Executing command: 'getlog'
DEBUG 2015-04-10 10:11:17,352: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
DEBUG 2015-04-10 10:11:17,359: 	 Checking credentials
DEBUG 2015-04-10 10:11:17,359: 	 Found proxy file /tmp/x509up_u23766
DEBUG 2015-04-10 10:11:17,359: 	 Getting proxy life time left
DEBUG 2015-04-10 10:11:17,762: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -timeleft
 output : 450345

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-10 10:11:18,165: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u23766 -actimeleft
 output : 450344

 error: Picked up _JAVA_OPTIONS: -Xmx256M

 retcode : 0
DEBUG 2015-04-10 10:11:18,165: 	 Proxy valid for 125:05:45 hours
ERROR 2015-04-10 10:11:18,166: 	 Working directory for task crab_MC_Powheg_Herwig_TT_CT10_AUET2_8TeV+ not found 
ERROR 2015-04-10 10:11:18,166: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.15/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.15/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.15/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 288, in __init__
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.15/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 397, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.15/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 382, in loadCache
    raise TaskNotFoundException(msg)
TaskNotFoundException: Working directory for task crab_MC_Powheg_Herwig_TT_CT10_AUET2_8TeV+ not found 
DEBUG 2015-04-10 10:28:25,833: 	 Executing command: 'kill'
DEBUG 2015-04-10 10:28:25,833: 	 Found /afs/desy.de/user/s/shwillia/.crab3 file
